"""
同步完整娃娃資料到 yanfei.db（來源：私服 etcitem_doll_power 表，332筆）
用法: python scripts/seed_dolls.py [--db path/to/yanfei.db]
"""
import sqlite3
import argparse
from pathlib import Path

DOLLS_DATA = [
    # (doll_type, bonus_value, note)
    # 來源: etcitem_doll_power, 同步日期 2026-03-19
    ("Doll_Ac", -1, "防禦-1"),
    ("Doll_Ac", -2, "防禦-2"),
    ("Doll_Ac", -3, "防禦-3"),
    ("Doll_Ac", -4, "防禦-4"),
    ("Doll_Hp", 10, "體力上限+10"),
    ("Doll_Hp", 15, "體力上限+15"),
    ("Doll_Hp", 20, "體力上限+20"),
    ("Doll_Hp", 25, "體力上限+25"),
    ("Doll_Hp", 30, "體力上限+30"),
    ("Doll_Hp", 35, "體力上限+35"),
    ("Doll_Hp", 40, "體力上限+40"),
    ("Doll_Hp", 45, "體力上限+45"),
    ("Doll_Hp", 50, "體力上限+50"),
    ("Doll_Mp", 10, "魔力上限+10"),
    ("Doll_Mp", 15, "魔力上限+15"),
    ("Doll_Mp", 20, "魔力上限+20"),
    ("Doll_Mp", 25, "魔力上限+25"),
    ("Doll_Mp", 30, "魔力上限+30"),
    ("Doll_Mp", 35, "魔力上限+35"),
    ("Doll_Mp", 40, "魔力上限+40"),
    ("Doll_Mp", 45, "魔力上限+45"),
    ("Doll_Mp", 50, "魔力上限+50"),
    ("Doll_HpTR", 10, "每32秒體力恢復10"),
    ("Doll_HpTR", 15, "每32秒體力恢復15"),
    ("Doll_HpTR", 20, "每32秒體力恢復20"),
    ("Doll_HpTR", 25, "每32秒體力恢復25"),
    ("Doll_HpTR", 10, "每64秒體力恢復10"),
    ("Doll_HpTR", 15, "每64秒體力恢復15"),
    ("Doll_HpTR", 20, "每64秒體力恢復20"),
    ("Doll_HpTR", 25, "每64秒體力恢復25"),
    ("Doll_HpTR", 30, "每64秒體力恢復30"),
    ("Doll_HpTR", 35, "每64秒體力恢復35"),
    ("Doll_HpTR", 40, "每64秒體力恢復40"),
    ("Doll_HpTR", 45, "每64秒體力恢復45"),
    ("Doll_HpTR", 50, "每64秒體力恢復50"),
    ("Doll_HpTR", 55, "每64秒體力恢復55"),
    ("Doll_HpTR", 60, "每64秒體力恢復60"),
    ("Doll_MpTR", 5, "每32秒魔力恢復5"),
    ("Doll_MpTR", 10, "每32秒魔力恢復10"),
    ("Doll_MpTR", 15, "每32秒魔力恢復15"),
    ("Doll_MpTR", 6, "每64秒魔力恢復6"),
    ("Doll_MpTR", 8, "每64秒魔力恢復8"),
    ("Doll_MpTR", 9, "每64秒魔力恢復9"),
    ("Doll_MpTR", 10, "每64秒魔力恢復10"),
    ("Doll_MpTR", 12, "每64秒魔力恢復12"),
    ("Doll_MpTR", 14, "每64秒魔力恢復14"),
    ("Doll_MpTR", 15, "每64秒魔力恢復15"),
    ("Doll_MpTR", 16, "每64秒魔力恢復16"),
    ("Doll_MpTR", 18, "每64秒魔力恢復18"),
    ("Doll_MpR", 2, "魔力恢復量+2"),
    ("Doll_Dmg", 1, "近距離攻擊+1"),
    ("Doll_Dmg", 2, "近距離攻擊+2"),
    ("Doll_Dmg", 3, "近距離攻擊+3"),
    ("Doll_Dmg", 4, "近距離攻擊+4"),
    ("Doll_Dmg", 5, "近距離攻擊+5"),
    ("Doll_Dmg", 6, "近距離攻擊+6"),
    ("Doll_Hit", 1, "近距離命中+1"),
    ("Doll_Hit", 2, "近距離命中+2"),
    ("Doll_Hit", 3, "近距離命中+3"),
    ("Doll_Hit", 4, "近距離命中+4"),
    ("Doll_Hit", 5, "近距離命中+5"),
    ("Doll_Hit", 6, "近距離命中+6"),
    ("Doll_DmgR", 15, "3%機率攻擊傷害+15"),
    ("Doll_DmgR", 15, "5%機率攻擊傷害+15"),
    ("Doll_Weight", 0, "負重能力+15%"),
    ("Doll_Weight", 0, "負重能力+7%"),
    ("Doll_Weight", 11, "現有負重 /1.1"),
    ("Doll_Weight", 12, "現有負重 /1.12"),
    ("Doll_Weight", 14, "現有負重 /1.14"),
    ("Doll_Weight", 16, "現有負重 /1.16"),
    ("Doll_Weight", 18, "現有負重 /1.18"),
    ("Doll_Weight", 20, "現有負重 /1.2"),
    ("Doll_Weight", 30, "現有負重 /1.3"),
    ("Doll_DmgBow", 1, "遠距離攻擊+1"),
    ("Doll_DmgBow", 2, "遠距離攻擊+2"),
    ("Doll_DmgBow", 3, "遠距離攻擊+3"),
    ("Doll_DmgBow", 4, "遠距離攻擊+4"),
    ("Doll_DmgBow", 5, "遠距離攻擊+5"),
    ("Doll_DmgBow", 6, "遠距離攻擊+6"),
    ("Doll_HitBow", 1, "遠距離命中+1"),
    ("Doll_HitBow", 2, "遠距離命中+2"),
    ("Doll_HitBow", 3, "遠距離命中+3"),
    ("Doll_HitBow", 4, "遠距離命中+4"),
    ("Doll_HitBow", 5, "遠距離命中+5"),
    ("Doll_DmgDown", 1, "傷害減免+1"),
    ("Doll_DmgDown", 2, "傷害減免+2"),
    ("Doll_DmgDown", 3, "傷害減免+3"),
    ("Doll_DmgDown", 4, "傷害減免+4"),
    ("Doll_DmgDown", 5, "傷害減免+5"),
    ("Doll_DmgDown", 6, "傷害減免+6"),
    ("Doll_DmgDownR", 15, "4%機率傷害減免+15"),
    ("Doll_Regist_Blind", 1, "暗黑耐性+1"),
    ("Doll_Regist_Blind", 3, "暗黑耐性+3"),
    ("Doll_Regist_Blind", 5, "暗黑耐性+5"),
    ("Doll_Regist_Blind", 7, "暗黑耐性+7"),
    ("Doll_Regist_Blind", 10, "暗黑耐性+10"),
    ("Doll_Regist_Freeze", 1, "寒冰耐性+1"),
    ("Doll_Regist_Freeze", 3, "寒冰耐性+3"),
    ("Doll_Regist_Freeze", 5, "寒冰耐性+5"),
    ("Doll_Regist_Freeze", 7, "寒冰耐性+7"),
    ("Doll_Regist_Freeze", 10, "寒冰耐性+10"),
    ("Doll_Regist_Sleep", 1, "睡眠耐性+1"),
    ("Doll_Regist_Sleep", 3, "睡眠耐性+3"),
    ("Doll_Regist_Sleep", 5, "睡眠耐性+5"),
    ("Doll_Regist_Sleep", 7, "睡眠耐性+7"),
    ("Doll_Regist_Sleep", 10, "睡眠耐性+10"),
    ("Doll_Regist_Stone", 1, "石化耐性+1"),
    ("Doll_Regist_Stone", 3, "石化耐性+3"),
    ("Doll_Regist_Stone", 5, "石化耐性+5"),
    ("Doll_Regist_Stone", 7, "石化耐性+7"),
    ("Doll_Regist_Stone", 10, "石化耐性+10"),
    ("Doll_Regist_Stun", 2, "昏迷耐性+2"),
    ("Doll_Regist_Stun", 3, "昏迷耐性+3"),
    ("Doll_Regist_Stun", 5, "昏迷耐性+5"),
    ("Doll_Regist_Stun", 7, "昏迷耐性+7"),
    ("Doll_Regist_Stun", 10, "昏迷耐性+10"),
    ("Doll_Regist_Sustain", 1, "支撐耐性+1"),
    ("Doll_Regist_Sustain", 3, "支撐耐性+3"),
    ("Doll_Regist_Sustain", 5, "支撐耐性+5"),
    ("Doll_Regist_Sustain", 7, "支撐耐性+7"),
    ("Doll_Regist_Sustain", 10, "支撐耐性+10"),
    ("Doll_Stat_Cha", 1, "魅力+1"),
    ("Doll_Stat_Cha", 2, "魅力+2"),
    ("Doll_Stat_Cha", 3, "魅力+3"),
    ("Doll_Stat_Con", 1, "體質+1"),
    ("Doll_Stat_Con", 2, "體質+2"),
    ("Doll_Stat_Con", 3, "體質+3"),
    ("Doll_Stat_Dex", 1, "敏捷+1"),
    ("Doll_Stat_Dex", 2, "敏捷+2"),
    ("Doll_Stat_Dex", 3, "敏捷+3"),
    ("Doll_Stat_Int", 1, "智力+1"),
    ("Doll_Stat_Int", 2, "智力+2"),
    ("Doll_Stat_Int", 3, "智力+3"),
    ("Doll_Stat_Str", 1, "力量+1"),
    ("Doll_Stat_Str", 2, "力量+2"),
    ("Doll_Stat_Str", 3, "力量+3"),
    ("Doll_Stat_Wis", 1, "精神+1"),
    ("Doll_Stat_Wis", 2, "精神+2"),
    ("Doll_Stat_Wis", 3, "精神+3"),
    ("Doll_Speed", 0, "人物速度 x1.33(1段加速)"),
    ("Doll_Water", 0, "能在水底呼吸"),
    ("Doll_Evasion", 1, "1%機率迴避攻擊一次"),
    ("Doll_Evasion", 2, "2%機率迴避攻擊一次"),
    ("Doll_Evasion", 3, "3%機率迴避攻擊一次"),
    ("Doll_Sp", 1, "魔攻+1"),
    ("Doll_Sp", 2, "魔攻+2"),
    ("Doll_Sp", 3, "魔攻+3"),
    ("Doll_Mr", 1, "魔法防禦+1"),
    ("Doll_Mr", 2, "魔法防禦+2"),
    ("Doll_Mr", 3, "魔法防禦+3"),
    ("Doll_DefenseEarth", 5, "地屬性防禦+5"),
    ("Doll_DefenseEarth", 10, "地屬性防禦+10"),
    ("Doll_DefenseEarth", 15, "地屬性防禦+15"),
    ("Doll_DefenseFire", 5, "火屬性防禦+5"),
    ("Doll_DefenseFire", 10, "火屬性防禦+10"),
    ("Doll_DefenseFire", 15, "火屬性防禦+15"),
    ("Doll_DefenseWater", 5, "水屬性防禦+5"),
    ("Doll_DefenseWater", 10, "水屬性防禦+10"),
    ("Doll_DefenseWater", 15, "水屬性防禦+15"),
    ("Doll_DefenseWind", 5, "風屬性防禦+5"),
    ("Doll_DefenseWind", 10, "風屬性防禦+10"),
    ("Doll_DefenseWind", 15, "風屬性防禦+15"),
    ("Doll_Mr", 4, "魔法防禦+4"),
    ("Doll_Mr", 6, "魔法防禦+6"),
    ("Doll_Mr", 8, "魔法防禦+8"),
    ("Doll_Mr", 10, "魔法防禦+10"),
    ("Doll_Mr", 12, "魔法防禦+12"),
    ("Doll_DmgDownR", 10, "4%機率傷害減免+10"),
    ("Doll_DmgDownR", 5, "4%機率傷害減免+5"),
    ("Doll_GetItem", 600, "每10分鐘給予阿魯巴的禮物1個"),
    ("Doll_Skill", 77, "3%機率施展「究極光裂術」"),
    ("Doll_Skill", 74, "3%機率施展「流星雨」"),
    ("Doll_Add_Skill", 26, "通暢氣脈術"),
    ("Doll_Add_Skill", 42, "體魄強健術"),
    ("Doll_Add_Skill", 48, "祝福魔法武器"),
    ("Doll_Add_Skill", 151, "大地防護"),
    ("Doll_Add_Skill", 148, "火焰武器"),
    ("Doll_Add_Skill", 149, "風之神射"),
    ("Doll_Add_Skill", 168, "鋼鐵防護"),
    ("Doll_Add_Skill", 163, "烈焰武器"),
    ("Doll_Add_Skill", 166, "暴風神射"),
    ("Doll_Exp", 30, "狩獵經驗值+20%"),
    ("Doll_Exp", 30, "狩獵經驗值+30%"),
    ("Doll_Exp", 40, "狩獵經驗值+40%"),
    ("Doll_Skill", 7, "3%機率施展「風刃」"),
    ("Doll_Skill", 46, "3%機率施展「烈炎術」"),
    ("Doll_Skill", 16, "3%機率施展「地獄之牙」"),
    ("Doll_Skill", 10, "3%機率施展「寒冷戰慄」"),
    ("Doll_Dmg", 7, "近距離攻擊+7"),
    ("Doll_Dmg", 8, "近距離攻擊+8"),
    ("Doll_Dmg", 9, "近距離攻擊+9"),
    ("Doll_Dmg", 10, "近距離攻擊+10"),
    ("Doll_DmgBow", 7, "遠距離攻擊+7"),
    ("Doll_DmgBow", 8, "遠距離攻擊+8"),
    ("Doll_DmgBow", 9, "遠距離攻擊+9"),
    ("Doll_DmgBow", 10, "遠距離攻擊+10"),
    ("Doll_Sp", 4, "魔攻+4"),
    ("Doll_Sp", 5, "魔攻+5"),
    ("Doll_Sp", 6, "魔攻+6"),
    ("Doll_Sp", 7, "魔攻+7"),
    ("Doll_Sp", 8, "魔攻+8"),
    ("Doll_Sp", 9, "魔攻+9"),
    ("Doll_Sp", 10, "魔攻+10"),
    ("Doll_Sp", 12, "魔攻+12"),
    ("Doll_Skill", 11, "3%機率施展「毒咒」"),
    ("Doll_Mp", 60, "魔力上限+60"),
    ("Doll_Mp", 70, "魔力上限+70"),
    ("Doll_Mp", 100, "魔力上限+100"),
    ("Doll_Mp", 150, "魔力上限+150"),
    ("Doll_DmgR", 15, "4%機率攻擊傷害+15"),
    ("Doll_DmgR", 20, "5%機率攻擊傷害+20"),
    ("Doll_DmgR", 25, "6%機率攻擊傷害+25"),
    ("Doll_DmgR", 30, "7%機率攻擊傷害+30"),
    ("Doll_DmgR", 45, "8%機率攻擊傷害+45"),
    ("Doll_Hp", 60, "體力上限+60"),
    ("Doll_Hp", 70, "體力上限+70"),
    ("Doll_Hp", 100, "體力上限+100"),
    ("Doll_Hp", 150, "體力上限+150"),
    ("Doll_Weight", 4, "現有負重 /1.04"),
    ("Doll_Weight", 8, "現有負重 /1.08"),
    ("Doll_DmgDownR", 20, "5%機率傷害減免+10"),
    ("Doll_DmgDownR", 25, "6%機率傷害減免+25"),
    ("Doll_DmgDownR", 30, "7%機率傷害減免+30"),
    ("Doll_DmgDownR", 45, "8%機率傷害減免+45"),
    ("Doll_HitBow", 7, "遠距離命中+7"),
    ("Doll_HpTR", 100, "每32秒體力恢復100"),
    ("Doll_HpTR", 150, "每32秒體力恢復150"),
    ("Doll_HpTR", 200, "每32秒體力恢復200"),
    ("Doll_HpTR", 250, "每32秒體力恢復250"),
    ("Doll_HpTR", 300, "每32秒體力恢復300"),
    ("Doll_HpTR", 450, "每32秒體力恢復450"),
    ("Doll_Ac", -5, "防禦-5"),
    ("Doll_MpTR", 20, "每32秒魔力恢復20"),
    ("Doll_MpTR", 25, "每32秒魔力恢復25"),
    ("Doll_MpTR", 30, "每32秒魔力恢復30"),
    ("Doll_MpTR", 45, "每32秒魔力恢復45"),
    ("Doll_Hp", 80, "體力上限+80"),
    ("Doll_Skill", 5000, "5%機率施展「火焰衝擊」"),
    ("Doll_Skill", 5001, "5%機率施展「爆擊火焰衝擊」"),
    ("Doll_MpTR", 3, "每64秒魔力恢復3"),
    ("Doll_MpTR", 5, "每64秒魔力恢復5"),
    ("Doll_Mr", 5, "魔法防禦+5"),
    ("Doll_Ac", -10, "防禦-10"),
    ("Doll_DmgDown", 7, "傷害減免+7"),
    ("Doll_DmgDownR", 15, "3%機率傷害減免+15"),
    ("Doll_Skill", 34, "3%機率施展「極道落雷」"),
    ("Doll_Regist_Stun", 8, "昏迷耐性+8"),
    ("Doll_Regist_Stun", 12, "昏迷耐性+12"),
    ("Doll_Skill", 5002, "5%機率施展「地獄火」"),
    ("Doll_StunLevel", 1, "昏迷等級+1"),
    ("Doll_StunLevel", 2, "昏迷等級+2"),
    ("Doll_HpTR", 30, "每32秒體力恢復30"),
    ("Doll_Weight", 0, "負重能力+3%"),
    ("Doll_Weight", 0, "負重能力+5%"),
    ("Doll_DmgDownR", 1, "4%機率傷害減免+1"),
    ("Doll_HpTR", 5, "每64秒體力恢復5"),
    ("Doll_Ac", -7, "防禦-7"),
    ("Doll_StunLevel", 3, "昏迷等級+3"),
    ("Doll_Skill", 29, "3%機率施展「緩速術」"),
    ("Doll_Weight", 0, "負重能力+6%"),
    ("Doll_Weight", 0, "負重能力+8%"),
    ("Doll_Weight", 0, "負重能力+9%"),
    ("Doll_Weight", 0, "負重能力+11%"),
    ("Doll_DmgDown", 8, "傷害減免+8"),
    ("Doll_DmgDown", 11, "傷害減免+11"),
    ("Doll_DmgDown", 14, "傷害減免+14"),
    ("Doll_DmgDown", 17, "傷害減免+17"),
    ("Doll_DmgDown_Npc", 20, "5%機率傷害減免+20"),
    ("Doll_Skill", 28, "3%機率施展「吸血鬼之吻」"),
    ("Doll_HpR", 2, "體力恢復量+2"),
    ("Doll_Skill", 33, "3%機率施展「木乃伊的詛咒」"),
    ("Doll_Weight", 0, "負重能力+4%"),
    ("Doll_MpTR", 2, "每64秒魔力恢復2"),
    ("Doll_MpTR", 20, "每64秒魔力恢復20"),
    ("Doll_Skill", 5003, "5%機率施展「金箍震擊」"),
    ("Doll_Skill", 5004, "5%機率施展「炎龍彈」"),
    ("Doll_Skill", 5005, "5%機率施展「流沙瀑布」"),
    ("Doll_Exp", 10, "狩獵經驗值+10%"),
    ("Doll_Exp", 15, "狩獵經驗值+15%"),
    ("Doll_Add_Skill", 79, "靈魂昇華"),
    ("Doll_Add_Skill", 68, "聖結界"),
    ("Doll_hp_potion", 2, "藥水恢復+2"),
    ("Doll_hp_potion", 3, "藥水恢復+3"),
    ("Doll_hp_potion", 6, "藥水恢復+6"),
    ("Doll_hp_potion", 9, "藥水恢復+9"),
    ("Doll_hp_potion", 15, "藥水恢復+15"),
    ("Doll_PVP", 3, "PVP增傷+3"),
    ("Doll_PVP", 6, "PVP增傷+6"),
    ("Doll_PVP", 9, "PVP增傷+9"),
    ("Doll_PVP", 15, "PVP增傷+15"),
    ("Doll_PVP_RED", 2, "PVP減傷-2"),
    ("Doll_PVP_RED", 4, "PVP減傷-4"),
    ("Doll_PVP_RED", 6, "PVP減傷-6"),
    ("Doll_PVP_RED", 10, "PVP減傷-10"),
    ("Doll_MagicHit", 1, "魔法命中+1"),
    ("Doll_MagicHit", 2, "魔法命中+2"),
    ("Doll_MagicHit", 3, "魔法命中+3"),
    ("Doll_MagicHit", 4, "魔法命中+4"),
    ("Doll_MagicHit", 5, "魔法命中+5"),
    ("Doll_MpR", 1, "魔力恢復量+1"),
    ("Doll_MpR", 3, "魔力恢復量+3"),
    ("Doll_MpR", 4, "魔力恢復量+4"),
    ("Doll_HpR", 1, "體力恢復量+1"),
    ("Doll_HpR", 3, "體力恢復量+3"),
    ("Doll_HpR", 4, "體力恢復量+4"),
    ("Doll_Exp", 3, "狩獵經驗值+3%"),
    ("Doll_Exp", 5, "狩獵經驗值+5%"),
    ("Doll_Exp", 7, "狩獵經驗值+7%"),
    ("Doll_Exp", 8, "狩獵經驗值+8%"),
    ("Doll_Exp", 9, "狩獵經驗值+9%"),
    ("Doll_Exp", 11, "狩獵經驗值+11%"),
    ("Doll_Exp", 13, "狩獵經驗值+13%"),
    ("Doll_Exp", 14, "狩獵經驗值+14%"),
    ("Doll_Exp", 18, "狩獵經驗值+18%"),
    ("Doll_Exp", 22, "狩獵經驗值+22%"),
    ("Doll_PVP_RED", 1, "PVP減傷-1"),
    ("Doll_Mp", 80, "魔力上限+80"),
    ("Doll_PVP_RED", 3, "PVP減傷-3"),
    ("Doll_Exp", 19, "狩獵經驗值+19%"),
    ("Doll_PVP", 2, "PVP增傷+2"),
    ("Doll_StunLevel", 6, "昏迷等級+6"),
    ("Doll_Regist_Stone", 8, "石化耐性+8"),
    ("Doll_Regist_Sustain", 8, "支撐耐性+8"),
    ("Doll_GetItem", 600, "每10分鐘給予天幣2000"),
    ("Doll_Dmg", 15, "近距離攻擊+15"),
    ("Doll_DmgBow", 15, "遠距離攻擊+15"),
    ("Doll_Hp", 300, "體力上限+300"),
    ("Doll_Sp", 15, "魔攻+15"),
    ("Doll_Hp", 250, "體力上限+250"),
    ("Doll_Exp", 50, "狩獵經驗值+50%"),
    ("Doll_StunLevel", 15, "昏迷命中+15"),
    ("Doll_Hp", 2000, "體力上限+2000"),
]


def seed(db_path: str) -> None:
    conn = sqlite3.connect(db_path)
    try:
        conn.execute("DELETE FROM dolls")
        conn.executemany(
            "INSERT INTO dolls (doll_type, bonus_value, note) VALUES (?, ?, ?)",
            DOLLS_DATA,
        )
        conn.commit()
        count = conn.execute("SELECT COUNT(*) FROM dolls").fetchone()[0]
        print(f"OK: 寫入 {count} 筆娃娃資料")
    finally:
        conn.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", default=str(Path(__file__).resolve().parent.parent / "data" / "yanfei.db"))
    args = parser.parse_args()
    seed(args.db)
